In [1]:
import torch
import torch.nn as nn

In [2]:
v = 4
d = 2
E = torch.randn(v,d, requires_grad=True)
E

tensor([[-0.3607, -0.4976],
        [-1.2192,  2.2165],
        [ 0.8557, -0.5750],
        [ 0.0025, -0.8335]], requires_grad=True)

In [3]:
def triangular(n):
    return n*(n+1)//2

In [4]:
v2 = triangular(v)
print(v2)

10


In [5]:
E2 = torch.zeros((int(v2), d), requires_grad=False)
E2

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
j = 0
for i, vec in enumerate(E):
    print(f"i: {i}")
    print(f"j: {j}")
    print(f"vec: {vec}")
    print(f"expanded vec: {vec.expand(v-i,d).shape}\n{vec.expand(v-i,d)}")
    print(f"spliced 2nd matrix: {E[i:,:].shape}\n{E[i:,:]}")
    print(f"[{j}:{j+v-i},:]")
    E2[j:j+v-i,:] += E[i,:].expand(v-i,d) + E[i:,:]
    print(f"E2: {E2.shape}\n{E2}")
    j += v-i

i: 0
j: 0
vec: tensor([-0.3607, -0.4976], grad_fn=<UnbindBackward0>)
expanded vec: torch.Size([4, 2])
tensor([[-0.3607, -0.4976],
        [-0.3607, -0.4976],
        [-0.3607, -0.4976],
        [-0.3607, -0.4976]], grad_fn=<ExpandBackward0>)
spliced 2nd matrix: torch.Size([4, 2])
tensor([[-0.3607, -0.4976],
        [-1.2192,  2.2165],
        [ 0.8557, -0.5750],
        [ 0.0025, -0.8335]], grad_fn=<SliceBackward0>)
[0:4,:]
E2: torch.Size([10, 2])
tensor([[-0.7215, -0.9952],
        [-1.5799,  1.7189],
        [ 0.4949, -1.0726],
        [-0.3582, -1.3311],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000]], grad_fn=<CopySlices>)
i: 1
j: 4
vec: tensor([-1.2192,  2.2165], grad_fn=<UnbindBackward0>)
expanded vec: torch.Size([3, 2])
tensor([[-1.2192,  2.2165],
        [-1.2192,  2.2165],
        [-1.2192,  2.2165]], grad_fn=<ExpandBackward0>)
spliced 2nd matrix: torch.Size(

In [10]:
def combination_embedding(E):
    v, d = E.shape
    E2 = torch.zeros((v*(v+1)//2, d), requires_grad=False)
    j = 0
    for i, vec in enumerate(E):
        E2[j:j+v-i,:] += E[i,:].expand(v-i,d) + E[i:,:]
        j += v-i

    return E2

In [17]:
test = torch.randn(65,4)
print(test)
E2 = combination_embedding(test)
print(E2.shape[0])

tensor([[ 0.7805,  0.8609,  0.6080, -0.3149],
        [-0.6034, -0.0507,  1.6488,  0.5085],
        [-0.5193, -0.5827, -0.9297, -0.2837],
        [ 1.7073, -0.7053,  0.2405,  0.1730],
        [-0.6074, -0.8870, -1.2033,  0.1397],
        [-1.6504,  0.1580, -0.7893,  0.4016],
        [ 0.0581, -1.0727, -0.1236,  0.3214],
        [-0.2835, -0.3713,  0.6168,  1.6662],
        [ 0.1200,  0.1332, -0.1708, -0.7695],
        [ 0.0816, -0.1551, -0.2668, -0.1468],
        [ 0.0272, -1.1563, -0.8942,  0.1306],
        [ 1.5876, -1.0553,  1.5033,  0.2858],
        [ 2.1168, -0.2589, -1.3682, -0.0186],
        [-1.1656,  1.6409, -0.7500,  0.6620],
        [ 0.6155,  0.0848, -1.3865,  1.1657],
        [ 0.9159, -1.6951,  0.8123,  0.1749],
        [-2.1635,  0.2846, -1.4025,  0.5925],
        [ 1.6073, -1.5286, -2.1382, -1.4981],
        [-0.9451, -1.0817,  0.4746, -1.2434],
        [ 1.7261, -0.3090,  0.3621, -0.1013],
        [-1.7278, -0.0735,  0.3864, -0.2759],
        [ 0.7784, -0.7094, -0.2681

In [18]:
E3 = combination_embedding(E2)
print(E3.shape[0])

2301585


I'm thinking maybe i can start off with some absurdly huge supertoken setup made from bytes and then use a method to trim it down to more interesting token combinations like in that one paper i just read [tokenization is more than compression](https://arxiv.org/pdf/2402.18376.pdf) to make the size actually manageable